spring:
#  数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie
    username: root
    password: 20030111
#  文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1000MB
#mybatis日志文件配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
#阿里云oss
aliyun:
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    accessKeyId: "LTAI5t9XJ494wcipCfhm9uk"
    accessKeySecret: "rKLkFj9KCciMrKy9tS8L4JwYqfemur"
    bucketName: "spring-talis"
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#    端口号
server:
  port: 7080