spring:
  #  数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie
    username: root
    password: 20030111
  redis:
    host: 192.168.111.100
    port: 6379
    password: 20030111
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  mail:
    username: Mr_Wangxy@outlook.com  #此处修改为你的邮箱帐号
    password: GDUFE7611  #此处为你的邮箱密码
    host:  smtp.office365.com
    port: 587
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  #  文件上传配置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 1000MB
#mybatis日志文件配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_ID
#阿里云oss
aliyun:
  oss:
    endpoint: "https://oss-cn-hangzhou.aliyuncs.com"
    accessKeyId: "LTAI5t9XJ494wcipCfhm9ukC"
    accessKeySecret: "rKLkFj9KCciMrKy9tS8L4JwYqfemur"
    bucketName: "redish"
#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#    端口号
server:
  port: 7080